### ISSUE TITLE
F14/f15 for brightness mapping

### ISSUE THREAD

**Issue by x4080** [RehabMan/OS-X-Voodoo-PS2-Controller#102]
Hi, since it will go to f14/f15 for brightness, we can then remap this using karabiner? Or customize it using plist?

**Comment by RehabMan** [comment]
You can change it in SysPrefs->Keyboard->Shortcuts.
Once you remove the assignment, you should be able to map them to something else in Karbiner Elements (if you want).
All key mapping can be changed within the kext via ACPI.

**Comment by x4080** [comment]
"All key mapping can be changed within the kext via ACPI."

How to do this?

**Comment by RehabMan** [comment]
Refer to the examples in the u430 and y50 projects.
It is based on ACPI RMCF overriding Info.plist entries.

**Comment by x4080** [comment]
Thanks, I'll take a look
