### ISSUE TITLE
Mapping Caps Lock to Command

### ISSUE THREAD

**Issue by bel3atar** [RehabMan/OS-X-Voodoo-PS2-Controller#103]
Results in command being pressed all the time.
To reproduce: System preferences => Keyboard => Modifier Keys

**Comment by RehabMan** [comment]
I assume you're on 10.12.
If so, "won't fix".  This is an artifact of the capslock bug work around.

**Comment by bel3atar** [comment]
I'm 10.12.1, does that make a difference?

**Comment by RehabMan** [comment]
My comment is applicable to all versions of 10.12 so far.

**Comment by emdriventodrink** [comment]
Same problem here.  I understand "won't fix."  Is there another way around this?  I'm using an old IBM model M and have limited choices for a command-key.  I pretty much have to remap CAPSLOCK to something.  Thanks much!

**Comment by DaiMaoTsai** [comment]
I understand "won't fix."  Is there another way around this?  I'm using an IBM model M and have limited choices for a command-key substitution.  I pretty much have to remap CAPS LOCK to *something*.  Thanks!

**Comment by RehabMan** [comment]
You can remap the key with ACPI "Custom ADB Map".
See the u430 repo (and keyboard remap wiki) for ideas.

**Comment by t-marvolo** [comment]
I'm trying to do the same thing as DaiMaoTsai, but can't figure out the PS2 scan codes I need. I've installed the debug kext and daemon, rebuilt caches and permissions and rebooted but I don't know where I'm supposed to see the scan codes.

Any help would be appreciated.

**Comment by DaiMaoTsai** [comment]
I wound up installing karabiner elements and used it to do the remapping.

https://github.com/tekezo/Karabiner-Elements

**Comment by t-marvolo** [comment]
Yeah I tried with karabiner elements too, but was having the same issue with the key sticking. 

If I watch with the karabiner event viewer, while caps is mapped to control for example, the release event happens BEFORE the press event (where it gets stuck). Pressing the actual control key then frees it from being stuck again. 

How do you have yours configured exactly?

**Comment by DaiMaoTsai** [comment]
Just one single remap does it for me.

![image](https://user-images.githubusercontent.com/6005016/27892718-22cf963a-61b6-11e7-986a-23347c86c8ac.png)

**Comment by t-marvolo** [comment]
Okay and you have the mapping in system prefs default? It seems karabiner overrides that anyway, but I'm not sure why I can't get it working. I guess I should just pick up a ps/2 to usb converter at this point.

**Comment by DaiMaoTsai** [comment]
Yes, I use the defaults and everything works great.  

![image](https://user-images.githubusercontent.com/6005016/27914900-69331d78-6219-11e7-904a-6b4f151f8251.png)


PS/2 to USB is probably a good idea since these devices will probably be orphaned at some point, even though mine shows no sign of aging.  Also Unicomp (original MFGR of the Model M) [makes new ones](http://www.pckeyboard.com/page/category/SpacesaverM) with MacOS keys.  Good luck

**Comment by t-marvolo** [comment]
Picked up the converter. It works fine now, but only with Karabiner. The system pref remapping doesn't seem to have any affect with the converter.

I've seen the bluetooth and usb mods around, maybe I will check them out one day.

**Comment by plumps** [comment]
As a follow-up for somebody else struggling with Karabiner Elements and a sticky CapsLock key. Here is what I did. 

```bash
diskutil mount /dev/disk0s1
open /Volumes/EFI/EFI/CLOVER/kexts/other/VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Keyboard.kext/Contents/Info.plist
```
And added the following key  to *IOKitPersonalities>ApplePS2Keyboard>Platform Profile>Default>Custom ADB Map*
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<string>3a=3d;swap caps_lock with right_option</string>
</plist>
```

**Comment by 4volodin** [comment]
> As a follow-up for somebody else struggling with Karabiner Elements and a sticky CapsLock key. Here is what I did.
> 
> ```shell
> diskutil mount /dev/disk0s1
> open /Volumes/EFI/EFI/CLOVER/kexts/other/VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Keyboard.kext/Contents/Info.plist
> ```
> 
> And added the following key to _IOKitPersonalities>ApplePS2Keyboard>Platform Profile>Default>Custom ADB Map_
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <string>3a=3d;swap caps_lock with right_option</string>
> </plist>
> ```

hi bro, did you have the problem like here ? https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/issues/194
