### ISSUE TITLE
BRIGHTNESS_DOWN

### ISSUE THREAD

**Issue by walkman8196** [RehabMan/OS-X-Voodoo-PS2-Controller#104]
Hello RehabMan
Thank you for a great kext
I use 10.12.1 with this kext. 
I pathed dsdt for brightness keys (_Q17/_Q18)  (I found them by RMDT methods)
Problem : in 10.12.1 not working key brightness down
I see your sources   
: BRIGHTNESS_UP,      // e0 17 hp up (Fn+F3)
 DEADKEY,// e0 18      // -  is not dead key

Can you help with this ??

**Comment by RehabMan** [comment]
It works just fine.  If you have an issue, use the forums.
