### ISSUE TITLE
Multi-finger gesture not working

### ISSUE THREAD

**Issue by duguzuyang** [RehabMan/OS-X-Voodoo-PS2-Controller#105]
on Dell XPS 13 9350 (i7 6560U Intel Iris 540)

Two-finger scrolling works perfect, multi-finger gesture does not work.

**Comment by RehabMan** [comment]
Three finger gestures must be configured in SysPrefs->Keyboard->Shortcuts.
Note: Not all gestures are supported (just because you see it in SysPrefs->Trackpad, does not mean it is implemented).

**Comment by trqukhanh0104** [comment]
Change key shortcut to Ctrl + Alt (or Option) + -> (or up, left, down arrow) to swipe space/desktop
