### ISSUE TITLE
Double click caps lock can not switch input method

### ISSUE THREAD

**Issue by SquallATF** [RehabMan/OS-X-Voodoo-PS2-Controller#106]
I used  10.12 with VoodooPS2Controller.kext 1.8.25
When I double click caps lock the input method icon changed and change back quickly.

**Comment by RehabMan** [comment]
You cannot change the function of the capslock with SysPrefs->Keyboard->Modifier Keys.  Changing the mapping at that level interferes with the work around for the 10.12 capslock bug.

If you wish to change the key assignment for capslock (some people switch it for Esc for some crazy reason), you must use "Custom ADB Map" to accomplish it.  You can create a custom ADB map via ACPI with RMCF.  Refer to my various projects for examples.
