### ISSUE TITLE
voodoo ps2 refuses to work on Sierra

### ISSUE THREAD

**Issue by opendata26** [RehabMan/OS-X-Voodoo-PS2-Controller#107]
I have installed Sierra on my hackintosh and installed the kext + daemon but it refuses to work.
OS: 10.12.2
SMBIOS: iMac14,2 
MOTHERBOARD: [GA-G31M-ES2L](http://www.gigabyte.com/products/product-page.aspx?pid=3134#sp)

**Comment by RehabMan** [comment]
The issues facility on github is not the appropriate place to troubleshoot.
Use the forums.
