### ISSUE TITLE
Documentation on how to debug issues

### ISSUE THREAD

**Issue by kenthinson** [RehabMan/OS-X-Voodoo-PS2-Controller#108]
Hello I was reading on tony Mac that the debug version of the kext will output debug logs. However I am not sure where to look to see the debug information. The wiki does not seem to have documentation on where to look. Can you point me in the right direction. Thank you.

**Comment by kenthinson** [comment]
Never mind found it by searching ps2 in the console. Now I just need to figure out why the touch point is only working sometimes.

**Comment by RehabMan** [comment]
Not an issue.
