### ISSUE TITLE
AlpsPS/2 ALPS DualPoint TouchPad not identified as a trackpad

### ISSUE THREAD

**Issue by sahdman** [RehabMan/OS-X-Voodoo-PS2-Controller#109]
I have a Lenovo E450 which has an AlpsPS/2 ALPS DualPoint TouchPad. This is not being detected as a trackpad, instead it is being used as a mouse. Does this driver support it?

Thanks.

**Comment by RehabMan** [comment]
There is support in this kext only for very old ALPS trackpads.
There are other forks of my code that support newer ALPS trackpads.
I have no ALPS hardware, so am not actively merging in such code.
