### ISSUE TITLE
No trackpad found after install

### ISSUE THREAD

**Issue by aiduryagin** [RehabMan/OS-X-Voodoo-PS2-Controller#116]
Which information i need to show to resolve this problem?

![screen shot 2017-02-12 at 22 54 21](https://cloud.githubusercontent.com/assets/6934028/22865488/a4c19176-f176-11e6-9c86-e5ca200316d2.png)

**Comment by RehabMan** [comment]
Use the forums (READ the README).
This is not the appropriate place to troubleshoot your mistake.
