### ISSUE TITLE
JP106 keyboard ID

### ISSUE THREAD

**Issue by since19861019** [RehabMan/OS-X-Voodoo-PS2-Controller#117]
VoodooPS2Controller IOMatch has the following key  for KBC.
<string>PNP0303</string>

Some Japanese laptops having keyboard 106 returns "PNP0320" as HID and I have to patch DSDT.
Will you add the next value in the Info.plist ? 
<string>PNP0320</string>

I have added the value and confirmed that it works.

**Comment by RehabMan** [comment]
Attach DSDT.aml for verification.

**Comment by since19861019** [comment]
[DSDT.aml.zip](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/files/863320/DSDT.aml.zip)

**Comment by RehabMan** [comment]
Fixed.  Will be in a future build.

**Comment by do-n-khanh** [comment]
Could you please release a build as soon as possible.
"future build v1.8.26
    Now matches on PNP0320 (Japanese keyboard). Fix for issue #117"

I dont have experience, I just know to download the build and put it on Kext Utility
