### ISSUE TITLE
when I change shortcut key to other keys then touchpad gesture changed too

### ISSUE THREAD

**Issue by aizigao** [RehabMan/OS-X-Voodoo-PS2-Controller#118]
I had changed mission control shortcut  from 'ctrl up'  to 'ctrl alt k', then touchpad gesture that three finger slide up maps none 😭 
can  I remap touchpad gesture?

**Comment by RehabMan** [comment]
The keyboard sequence generated by VoodooPS2Keyboard is in the Info.plist, therefore customizable with ACPI.
Refer to ActionSwipeUp, ActionSwipeDown, ActionSwipeLeft, ActionSwipeRight and the related code.
Refer to *.dsl for examples of ACPI customization.
