### ISSUE TITLE
SynapticsTouchPad cant zoom（Just like magnify the picture）

### ISSUE THREAD

**Issue by dgtutu** [RehabMan/OS-X-Voodoo-PS2-Controller#120]
Why the VoodooPS2Controller.kext  can't  make my SynapticsTouchPad zoom in Hackintosh(10.12.x)（Just like magnify the picture），Can you fix it ，Thx ：）

**Comment by tluck** [comment]
Zoom (full screen or PIP) works for my Synaptics Touchpad ? did you enable in Accessibility?

**Comment by dgtutu** [comment]
eh ？Where can ienable it ，info.plist  or touchpad setting？I am sure I had enabled it in touchpad setting

**Comment by tluck** [comment]
are you using latest VoodooPS2 for Sierra support?  nothing to change in kext/info.plist that i know of. 
1) you enable scrolling in TrackPad SysPref. 
2) then in sys-pref Accessibility - enable Control + Scroll to Zoom full screen.

**Comment by dgtutu** [comment]
Yes，I‘m using latest VoodooPS2 for Sierra support
All in the trackpad  syspref what I can see that I had enable ，but I still can’t zoom

**Comment by dgtutu** [comment]
My trackpad syspref  at the very start （I just reinstall the system） which is not shown anything(it's white) in Preference setting，Only I had installed Acpibatterymanager can I change the setting in it

**Comment by dgtutu** [comment]
I download VoodooPS2 from github and  I Compiled it with xcode by myself，and put it into clover/kext/10.12 ，now I can use my two finger to roll ，but only zoom I can't use it

**Comment by tluck** [comment]
test zoom with USB mouse - which has nothing to do with VoodooPS2Controller.

**Comment by dgtutu** [comment]
‘test zoom with USB mouse - which has nothing to do with VoodooPS2Controller.’
I use Roller + command/ctrl /^  in my  mouse can‘t zoom anything

**Comment by tluck** [comment]
did you enable zoom in Accessibility?

**Comment by dgtutu** [comment]
Yes。。。

**Comment by tluck** [comment]
well if you cannot zoom with USB mouse - then it is not a problem with VoodooPSController.

i have an Apple Magic mouse, USB mouse, and Synaptics TrackPad (via VoodooPS2Controller) - all work the same with Control+Scroll.

**Comment by dgtutu** [comment]
Follow your advice ，I can zoom with Control+Scroll in the Pictures app，but the xxx.jpg in finder still can’t zoom it，it  will only move

**Comment by dgtutu** [comment]
I opened the amplification through the auxiliary function, but it is only the entire screen to enlarge, I just want to enlarge a picture like the windows system。。。。。。。。

**Comment by dgtutu** [comment]
I want my trackpad like command + ‘+’

**Comment by tluck** [comment]
you can use PIP (small zoom window) - instead of full screen zoom
or use file preview feature - select an image file in finder - hit space bar. 
but this not the forum to learn macOS

**Comment by dgtutu** [comment]
![dc7739aa-9503-4ede-852e-5bb40489f4f2](https://cloud.githubusercontent.com/assets/22521103/24867917/32a0765a-1e41-11e7-94df-1cedabeed5e8.png)
Why can't I use two fingers to zoom in, but I have to add a command key, like this

**Comment by dgtutu** [comment]
![fc6ca9b8-2927-4cf1-a439-33394dbf6548](https://cloud.githubusercontent.com/assets/22521103/24868017/69f91454-1e41-11e7-9a31-8d4ef016b354.png)
I don't want this way+ command to zoom......
OH ,which make me sadlly

**Comment by dgtutu** [comment]
![b3f6b69b-17e7-40ff-ba32-fb594570e2a1](https://cloud.githubusercontent.com/assets/22521103/24868232/f4ff5fcc-1e41-11e7-9adf-ae2b5b56c81b.png)

I've got all the options

**Comment by tluck** [comment]
ah - well 2 finger Pinch/Expand to Zoom is not implemented in the software driver. so is not a working gesture.

**Comment by dgtutu** [comment]
So I just want Dear Mr. rehabman add the function....in the software driver。。。。

**Comment by RehabMan** [comment]
No plans to implement pinch/zoom.
