### ISSUE TITLE
Experiencing choppy/rough scrolling on X220

### ISSUE THREAD

**Issue by samloeschen** [RehabMan/OS-X-Voodoo-PS2-Controller#124]
Hey, installed this via [John Mcdonnell's X220 Sierra Guide](http://x220.mcdonnelltech.com/). I'm currently experiencing very rough scrolling (feels like 20-30 fps) in most applications when using two finger scroll on Sierra 10.12.5. The behavior is strange because scrolling via trackpoint + middle click, or inertial scrolling runs at a smooth 60 fps. Is there a good way to remedy this?

**Comment by RehabMan** [comment]
Not enough details.  You should use the forums.

**Comment by RehabMan** [comment]
Closed due to lack of feedback/info.
