### ISSUE TITLE
USBMouseStopsTrackpad doesn't work

### ISSUE THREAD

**Issue by favadi** [RehabMan/OS-X-Voodoo-PS2-Controller#125]
macOS version: 10.12.5
Machine: Dell Precision 5510

Steps to reproduce:
* change `USBMouseStopsTrackpad` to 1 in `VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Trackpad.kext/Contents/Info.plist`.
* reboot
* plugin USB mouse

Expected behavior: trackpad stop receiving input

Actual behavior: trackpad still works

**Comment by RehabMan** [comment]
It is known issue that VoodooPS2Daemon is not working in 10.12...

**Comment by favadi** [comment]
I assume that it is #127? In that case I will close this issue.

**Comment by RehabMan** [comment]
Separate issue.
The daemon does not work in Sierra either...
It is just something I have not gotten around to fixing.

**Comment by RehabMan** [comment]
This is fixed in v1.8.28.
