### ISSUE TITLE
Pointer speedup and scroll slowdown?

### ISSUE THREAD

**Issue by JurekRaben** [RehabMan/OS-X-Voodoo-PS2-Controller#130]
Hi,

this driver works excellently, on my Sony VAIO F11 basic touchpad.

The only problem: The mouse cursor is quite slow, and the right border for scrolling is extremely fast.

Are there config options to change those speeds?  If so, where to find an example and if not, I would like to request these parameters to be added.

Thanks.

**Comment by RehabMan** [comment]
SysPrefs->Trackpad.
