### ISSUE TITLE
Driver not loading on PNP0303/DLLK062B since 5b62873

### ISSUE THREAD

**Issue by OttoEdler** [RehabMan/OS-X-Voodoo-PS2-Controller#131]
The trackpad on my Dell Latitude E5450 doesn't work with the latest binary (July 22). In IORegistryExplorer there is no driver loaded on PS2M device. It used to work with earlier versions.

**Comment by RehabMan** [comment]
Use the forums to provide "Problem Reporting" files.
Read FAQ, "Problem Reporting"
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/

**Comment by OttoEdler** [comment]
I don't use tonymacx86.com. Should I attach ioreg with working trackpad drivers or with your latest binary?

**Comment by RehabMan** [comment]
I'm not providing support here.
Only on tmx.
Your choice.

**Comment by OttoEdler** [comment]
Why do you spread your projects across 3 platforms? I don't see a good reason, since all essential features are available here.

**Comment by RehabMan** [comment]
No idea what you mean by "3 platforms".

**Comment by OttoEdler** [comment]
github.com, bitbucket.org and tonymacx86.com

**Comment by RehabMan** [comment]
github is used as primary source code repo.
But github provides no download facility for builds (it used to, then it was discontinued).
Hence downloads are on bitbucket.
bitbucket also serves as a redundant location for source code.
tonymacx86.com is for support.

**Comment by OttoEdler** [comment]
release page is the place to provide builds for download, this issue page is for reporting, organization and support. i still don't see a reason to use those forums, that are in focus of criticism for good reason. but fine, your choice, i'm on in a position to argue with that. at least you know that there is an issue with the latest version of this project.

**Comment by RehabMan** [comment]
Release page did not exist when I started on github.
I'm not going to change now.  No benefit.

There is no issue.  I'm using the latest build without a problem.
Please use the forums to troubleshoot your issue.
