### ISSUE TITLE
Some keys don't work as it should

### ISSUE THREAD

**Issue by beBoss** [RehabMan/OS-X-Voodoo-PS2-Controller#132]
z, x, n, f, g, t, u

Most of the time these keys don't work. Have to hold them and wait until they get to work, or have to press it again. Sometimes they repeat themself. It's really hard to use this keyboard :(

Every time when there is a new version of the Voodoo-PS2-Controller kext(I use Kext Utility) file I am up to date with it, but without any difference.

MacOS Sierra 10.12.6 (16G29)
Lenovo Y510P

**Comment by RehabMan** [comment]
This  is not the place to troubleshoot your issue.
Use the forums.
