### ISSUE TITLE
Trackpad and Keyboard randomly stop working 

### ISSUE THREAD

**Issue by TheForgottenKing** [RehabMan/OS-X-Voodoo-PS2-Controller#134]
HP Envy M6 1125DX

i5 3210m
HD 4000

Works most of the time, but maybe one out of 50 boots, the trackpad and keyboard don't work and I must reboot using the power button for a few seconds

Also stops occasionally during standard use, only happened twice in a few weeks of using this.

Using newest driver

**Comment by RehabMan** [comment]
Use the forums. This is not the appropriate place to troubleshoot your configuration.
