### ISSUE TITLE
VoodooPS2controller Clover versions > 4080

### ISSUE THREAD

**Issue by jonathanburgossaldivia** [RehabMan/OS-X-Voodoo-PS2-Controller#135]
1) Your kext Voodoops2controller is not injected into Clover versions higher than 4080 I do not know why, can you help me with that? 

2) your daemons is working again, trackpad works as native works very well in macOS 10.13, thanks...

**Comment by RehabMan** [comment]
Use the forums:
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/
