### ISSUE TITLE
Trackpad Pane is blank in system config on High Sierra

### ISSUE THREAD

**Issue by goagain** [RehabMan/OS-X-Voodoo-PS2-Controller#136]
My laptop is HP Spectre X360, kabylake version, it use Synaptics SMBus TouchPad. The details I can got is HID\VEN_ELAN&DEV_0732&Col01.

under High Sierra, the trackpad can move , press click, double finger scroll.  but can't tap, three finger, four finger, or do other gestures.

**Comment by goagain** [comment]
![4k2 ttfrhshh tf zzq1u29](https://user-images.githubusercontent.com/6624474/31016914-3c42dca8-a559-11e7-8fb5-1c715d08b978.jpg)
![6 y tk 0037 p 8 k5csw](https://user-images.githubusercontent.com/6624474/31016917-3da5745c-a559-11e7-8c1e-3280fd0a7c2a.png)
![oqwwe554t3xm1kkqbu14b v](https://user-images.githubusercontent.com/6624474/31016921-3f73db02-a559-11e7-8d24-0c5f01df41ca.png)
![89s4uz917vo m g tm13d](https://user-images.githubusercontent.com/6624474/31016924-410b03dc-a559-11e7-9426-3037bdd1a606.png)
![lu au g s k gjt t](https://user-images.githubusercontent.com/6624474/31016925-4280bd06-a559-11e7-87ec-9a36760cdeec.png)

**Comment by RehabMan** [comment]
Use the forums:
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/

**Comment by bySabi** [comment]
@goagain, same here ...
you solved it?

**Comment by RehabMan** [comment]
Use the forums:
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/
