### ISSUE TITLE
Xcode 6.x not supported on Sierra ;(

### ISSUE THREAD

**Issue by hevisko** [RehabMan/OS-X-Voodoo-PS2-Controller#138]
Good day,

 I'd like to test my changes etc. but I only have Sierra available and XCode 6.1 is blatantly not launchable on Sierra (unless you start to do hackery to get some old framework from somewhere: http://indiestack.com/2016/08/xcode-6-on-sierra/ )

Any advice going forward? is XCode8 usable instead of 9 for this project?

**Comment by RehabMan** [comment]
Currently using Xcode 9, with SDK 10.8.
