### ISSUE TITLE
NumPad Dot not Working on Desktop Computers

### ISSUE THREAD

**Issue by joaodforce** [RehabMan/OS-X-Voodoo-PS2-Controller#139]
So I'm using the latest VoodooPS2 on my desktop, I have a ABNT2 Layout Keyboard,
The Dot Key right over the NumPad Enter key, does not work correctly, first I thought it was a keyboard layout issue, but changing it seem to have no effect, and setting the right ABNT2 Layout gives me the following results:

The first time I press the Dot key, it registers correctly, but when I press it a second time, it holds it until i press another key, afterwards it doesn't register it at all.
I thought it was a hardware issue, so i took it apart and cleaned, and tested it on windows, where it works normally.

Here is a pic of my keyboard just in case.
![23313122_1516863025071634_1949871971_o](https://user-images.githubusercontent.com/9410916/32491840-515218f2-c39f-11e7-9e85-049509994edd.jpg)

**Comment by RehabMan** [comment]
You need to look at your kernel logs with the debug version installed (or with LogScanCodes 1).
Read the wiki for ideas.
