### ISSUE TITLE
Switched keys.

### ISSUE THREAD

**Issue by drasbeck** [RehabMan/OS-X-Voodoo-PS2-Controller#140]
In the build of 2017-0901 I'm observing two keys being completely switched, i.e. pressing one key yields what the other key under normal circumstances would output and vice versa. I've marked the affected keys on the picture below. Is this behavior on purpose? And can it be changed? It's a minor nuisance when programming where the $§ and especially <> symbols are utilized. BTW: I'm using Danish layout on a ThinkPad T430.

The keys that have been switched:
<img src="https://user-images.githubusercontent.com/8578706/32703317-4ed4ea2e-c7f4-11e7-97b5-4c69e5387c98.jpg" width="300">

If it's of any help to you, here's the keyboard viewer from the T430:
![screen shot 2017-11-12 at 21 58 35](https://user-images.githubusercontent.com/8578706/32703351-18ebf21c-c7f5-11e7-971c-3d4a9be7af45.png)

And here's the keyboard viewer using the same layout on my MacBook:
<img width="469" alt="screen shot 2017-11-12 at 21 59 01" src="https://user-images.githubusercontent.com/8578706/32703408-d53c010a-c7f5-11e7-8bab-991c5c563f8a.png">

One thing I see from this is that it seems on the full size keyboard the key to the left of 'Z' (normally providing '<' and '>') seems to be missing entirely. This is also the case when I look up the layout on my Mac mini, yet the key _does_ exist as is shown in this picture:
<img src="https://user-images.githubusercontent.com/8578706/32703561-17690abc-c7f8-11e7-8a50-3e4d4ff0a3a5.jpg" width="300">

**Comment by RehabMan** [comment]
Your issue is not related to this kext.
You can change your keymap using Ukelele.

**Comment by drasbeck** [comment]
I agree on your assessment.

For me, this issue was somehow automatically resolved a couple of days after I posted. And the keyboard layout has been working as expected since then. Even through a macOS upgrade.
