### ISSUE TITLE
mapping FN

### ISSUE THREAD

**Issue by Ravenso** [RehabMan/OS-X-Voodoo-PS2-Controller#141]
Hello

I have a normal keyboard PC. When I click on the Insert button, it displays the letter "v". I tried to change the Custom ADB Map in the defaulit of the section "e052 = 3f" so that the FN button was pressed. Now nothing happens at all

How can I do it?

**Comment by RehabMan** [comment]
Use the forums.  This is not the correct place for troubleshooting.
