### ISSUE TITLE
Suggestion: three-finger-swipes generate mission control keycodes

### ISSUE THREAD

**Issue by KireinaHoro** [RehabMan/OS-X-Voodoo-PS2-Controller#143]
The default keyboard shortcut for mission control (`⌘↑`, etc) are quite useful, and is easy to get used to; while the touchpad generates keycodes of `^⌘↑`, etc keycodes for now. Can we make the three-finger-swipes generate keycodes that correspond to Mission Control operations?

In the following manner: 
 - three-up for `⌘↑`
 - three-down for `⌘↓`
 - three-left for `⌘→` (naturally for scrolling between workspaces)
 - three-right for `⌘←`

**Comment by RehabMan** [comment]
I have my reasons for these defaults...

You can configure it via ACPI if you wish.  Just override the ActionSwipeUp, ActionSwipeDown, ActionSwipeLeft and ActionSwipeRight.

For example, the SSDT would look like this:
```
// This sample shows how to remap the the default swipes to Option+Arrows,
// instead of the Ctrl+Option+Arrows
DefinitionBlock ("", "SSDT", 2, "hack", "ps2", 0)
{
    Name(_SB.PCI0.LPCB.PS2K.RMCF, Package()
    {
        "Keyboard", Package()
        {
            "ActionSwipeUp", "37 d, 7e d, 7e u, 37 u",
            "ActionSwipeDown", "37 d, 7d d, 7d u, 37 u",
            "ActionSwipeLeft", "37 d, 7b d, 7b u, 37 u",
            "ActionSwipeRight", "37 d, 7c d, 7c u, 37 u",
        },
    })
}
//EOF
```
You can see the defaults include Ctrl (down, then up)... eg. default ActionSwipeUp is: 3b d, 37 d, 7e d, 7e u, 37 u, 3b u
Look at VoodooPS2Keyboard.kext/Contents/Info.plist.
You can override any of the configuration data with ACPI.

ADB code 3b corresponds to Ctrl.
You can probably guess the other codes, or look them up in VoodooPS2Keyboard.cpp.

I will add SSDT-AlternateSwipes.dsl as an example file in the project.
