### ISSUE TITLE
Остановлена загрузка Clover: VoodoPS2SynapticsTouchPad (Mouse, TrackPad)

### ISSUE THREAD

**Issue by xricson** [RehabMan/OS-X-Voodoo-PS2-Controller#145]
Ошибка загрузки Clover:
VoodooPS2SynapticsTouchPad .............. 16,7
VoodooPS2SynapticsMouse      ............. 16,3
VoodooPS2SynapticsTrackPad   ..............  7,5

**Comment by RehabMan** [comment]
Use the forums (and English).
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/
