### ISSUE TITLE
voodoo-ps2- controller  freeze and crash

### ISSUE THREAD

**Issue by fixpol** [RehabMan/OS-X-Voodoo-PS2-Controller#148]
I have just upgraded to 10.13.4 and  using  Ps-2 mouse is almost not possible as   computer  freezes with no response or crashes.
Using other  radio mouse or bluetooth  is fine.  So only reason can be ps2 controller kext. Please advise if there is any fix or must resign of Ps2 interface.

**Comment by RehabMan** [comment]
Use the forums so you can provide full problem reporting files as per FAQ:
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/
