### ISSUE TITLE
Caps Lock button backlight feedback is often wrong.

### ISSUE THREAD

**Issue by yaozaiyu** [RehabMan/OS-X-Voodoo-PS2-Controller#154]
When I was using Voodoo-PS2-Controller, I was crazy to press the Caps Lock button backlight feedback frequently wrong. But when I used ApplesmartTouchpad, all of this was normal. I hope to make a quick patch.

**Comment by RehabMan** [comment]
I'm not able to reproduce the issue you're reporting. 

Please use the forums for proper troubleshooting.
There is no issue with capslock on any of the three laptops I have here.

**Comment by yaozaiyu** [comment]
Hello, is your system format APFs?

**Comment by RehabMan** [comment]
I have some running APFS, others HFS+J.
But what does that have to do with capslock/ps2?

**Comment by yaozaiyu** [comment]
I solved the problem，thanks！

**Comment by Raymonf** [comment]
@yaozaiyu How did you solve it?

**Comment by yaozaiyu** [comment]
![85f81e79-22f4-489e-86d0-8e8774535116](https://user-images.githubusercontent.com/25170955/39460664-da3543ac-4d37-11e8-9eee-26c222d9d080.png)
close the tab。

**Comment by Raymonf** [comment]
Ah, it must have been an IME bug for you. That option doesn't exist for me. Whatever.

![image](https://user-images.githubusercontent.com/8991740/39460774-2967358e-4cd4-11e8-8c52-9e791554db59.png)

**Comment by yaozaiyu** [comment]
直接将中文好了，你要先添加一个输入法，在左下角的地方，然后就会出现我上面的选项了

**Comment by Raymonf** [comment]
@yaozaiyu 原來如此！謝謝！

(In English: The solution is to add an official Apple input method editor to uncheck "use 'US' as the keyboard layout when caps lock is enabled". It's caused by having a Chinese IME.)
