### ISSUE TITLE
HP4340s Trackpad after sleep

### ISSUE THREAD

**Issue by Treamz** [RehabMan/OS-X-Voodoo-PS2-Controller#155]
hello, made this guide https://www.tonymacx86.com/threads/...book-zbook-using-clover-uefi-hotpatch.232948/
replaced wifi only
and everything works fine, it's set to 10.13
Laptop HP 4340s 
but after sleep the trackpad does not want to work, is there a solution?
[SSDT CLOVER.zip](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/files/2068236/SSDT.CLOVER.zip)

**Comment by RehabMan** [comment]
Use the forums, such that you can attach full "Problem Reporting" files as requested in the guide/FAQ.
