### ISSUE TITLE
Only works with keyboard

### ISSUE THREAD

**Issue by twikoffin** [RehabMan/OS-X-Voodoo-PS2-Controller#163]
I have Dell 3576 laptop on i5 8250u. 
Keyboard is works, but touchpad won't.
![2018-08-14 10 24 29](https://user-images.githubusercontent.com/32393163/44077407-41b5a712-9fac-11e8-8015-e30e8a13f469.png)

Some information from Windows 10:
![_47a8hvwj-w](https://user-images.githubusercontent.com/32393163/44077491-8e072410-9fac-11e8-8753-e922c4db3975.jpg)
![sadfeagthsrewqetntrtrwtrrh4wgrht5w](https://user-images.githubusercontent.com/32393163/44077559-c31d1100-9fac-11e8-9b50-c4bcf2d41bb5.jpg)

**Comment by RehabMan** [comment]
Your trackpad may be I2C, not PS2.
You should use the forums for troubleshooting, not github issues.
