### ISSUE TITLE
Trackpad + Mouse doesn't work on High Sierra on ASUS UX330UAR

### ISSUE THREAD

**Issue by AwlsomeAlex** [RehabMan/OS-X-Voodoo-PS2-Controller#165]
I used an older version of Voodoo PS2 Controller from another guide with a similar device, but after updating the kext other directory (Clover) in the EFI partition of the installer USB I created, it doesn't work. Not even with a mouse. Where do I put the VoodooPS2Daemon on an installer disk?

**Comment by RehabMan** [comment]
Your trackpad is probably I2C, not PS2.
