### ISSUE TITLE
OS-X-Voodoo-PS2-Controller does not work on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by Jankela121** [RehabMan/OS-X-Voodoo-PS2-Controller#167]
macOS 10.14 Mojave does not support OS-X-Voodoo-PS2-Controller and that should be fixed real quick considering that Mojave was released 15 days ago. Installing this .kext file with Kext Utility on macOS 10.14 Mojave will make the OS unbootable and it will enter kernel panic and then gets trapped in a restart loop.

**Comment by RehabMan** [comment]
It works just fine.  Use the forums for troubleshooting your issue.
