### ISSUE TITLE
fn key / fkey swap

### ISSUE THREAD

**Issue by Memphiz** [RehabMan/OS-X-Voodoo-PS2-Controller#168]
I have an odd problem.

I have El Capitan, High Sierra and Mojave installed. I have the Elitebook 8570p.

In none of those 3 macos installations i have the "fn key swap" option in the settings->keyboard prefpane.

In El Capitan and Mojave my Fkeys default to simply FKeys ( which i prefer )
In High Sierra my FKeys default to the fn + fkey function and i need to press FN in addition to get the real FKey triggers.

The only difference is that the High Sierra is a fresh installation while el Captian and Mojave are updates which go back to osx 10.8 or 10.9 for a start.

The key combination ctrl+shit+fn+printscr works to toggle that behavior - but that toggle is only tempoarily and doesn't tick between reboots.

How can i make that setting stick between reboots or how can the checkbox in the keyboard prefpane be made visible again?

Also i noted that the SSDT-8x70.dsl includes KEY-87.dsl even though the elitebook 8570p has a keycount of 102 keys.

Overall i am confused ;)  because all hotpatches and kexts are identical in all 3 installations ...

**Comment by RehabMan** [comment]
It is not there in SysPrefs because Apple removed it.
You can still change it in Karabiner (last I checked).
