### ISSUE TITLE
VoodooPS2Keyboard doesn't start

### ISSUE THREAD

**Issue by ghost** [RehabMan/OS-X-Voodoo-PS2-Controller#173]
here's my system log with `grep Voodoo`
![screen shot 2018-11-23 at 06 55 31](https://user-images.githubusercontent.com/42888358/48949460-df3fe800-eeec-11e8-83a9-94efea3f2397.png)
As you can see it loads Trackpad then Mouse then Keyboard and Controller. Then when it runs Trackpad it fails and doesn't seem to run other 3. Because of that my keyboard is not working. My touchpad has a physical problem, it just doesn't work anywhere, but keyboard doesn't have one. So here's my question:
Is touchpad failing and then everything else after it not running because of that?
If so please fix it as quickly as possible, or at least give me a tip to change the order or disable touchpad check.

**Comment by RehabMan** [comment]
Please use the forums.  The information you provided here is not enough to diagnose the issue.
