### ISSUE TITLE
command key not working???

### ISSUE THREAD

**Issue by jekoie** [RehabMan/OS-X-Voodoo-PS2-Controller#177]
hi, i use thinkpad t460 on   Mac OS 10.14.2, but windows key can not reflect command key, when i use windows + C, or windows + P, the keyboard input special chars(not copy&paste operation), how can i solve it???

**Comment by wsy** [comment]
In Info.plist, there's "Swap command and option" setting and it's "<true />" by default.
And normally Rehabman will suggest that you ask questions in the forum, not on GitHub.

**Comment by jekoie** [comment]
ok thanks
