### ISSUE TITLE
HiMans

### ISSUE THREAD

**Issue by Aljeksandr** [RehabMan/OS-X-Voodoo-PS2-Controller#179]
how to reserve,bind, (the value of the combination ctrl + (4 or 5or 6  (not numpad))) on the key for example 56 mostly on non-US keyboards qwertz keyboard hp.

**Comment by Aljeksandr** [comment]
my key have #56 ApplePS2Keyboard: sending key 56=3c(how ctrl+4), now i edit to 
3C-F2, default key value #56=a;default sending key 56=3c

**Comment by RehabMan** [comment]
This kext does not deal with "combination keys".  Control and the '4' key are sent/handled/mapped separately.
