### ISSUE TITLE
Synaptics (trackpad portion) *two-finger scroll only* speed is too slow (normal speed is fine)

### ISSUE THREAD

**Issue by steakknife** [RehabMan/OS-X-Voodoo-PS2-Controller#183]
- Hardware: Lenovo T480 (20L5)

Any ideas on adding more acceleration or more movement to two-finger scrolling? I'm guessing (but probably wrong) `MomentumScrollTimer` and `MomentumScrollMultiplier`.

I use the trackpad but not the trackpoint, and accustomed to the A1278 MBP trackpad.

I was browsing IORegistryExplorer & IOJones

at `IOService:/AppleACPIPlatformExpert/MOU/ps2controller/ApplePS2Controller/ApplePS2MouseDevice/ApplePS2SynapticsTouchPad`

```
HorizontalScrollDivisor 0x0

MomentumScrollDivisor 0x64
MomentumScrollMultiplier 0x62
MomentumScrollSamplesMin 0x3
MomentumScrollThreshY 0x12
MomentumScrollTimer 0x989680
MouseMomentumScroll True
MouseScrollMultiplierX 0x2
MouseScrollMultiplierY 0x2
MultiFingerHorizontalDivisor 0xd
MultiFingerVerticalDivisor 0xd
MultiFingerWLimit 0x9

ScrollDeltaThreshX 0x0
ScrollDeltaThreshY 0x0
ScrollResolution 0x320
SwipeDeltaX 0x320
SwipeDeltaY 0x320

Thinkpad True

TrackpadHorizScroll 0x1
TrackpadMomentumScroll True
TrackpadScroll True

VeritcalScrollDivisor 0x0
```

Otherwise, it's working pretty awesomely. 👍

**Comment by RehabMan** [comment]
Refer to *.dsl for Thinkpad specific configuration.
