### ISSUE TITLE
Scroll speed and right click tapping.

### ISSUE THREAD

**Issue by mallgrab** [RehabMan/OS-X-Voodoo-PS2-Controller#185]
Hey! The kext works pretty alright but there are some things that I want to tweak.

Scroll speed seems to be really slow, tweaking the touchpad settings doesn't make it fast enough even on max settings. 

Also is it possible to tweak the timing whenever you two finger tap?

**Comment by mallgrab** [comment]
Tweaking ScrollResolution did it for me.
Still, is there no way to configure the threshold of tapping with two fingers to right click?
It's as if both fingers have to tap at the exact moment. If one finger lands just a few milliseconds too late the right click never happens.

**Comment by mallgrab** [comment]
Tweaking ScrollResolution fixed the slow scroll speed.

Timing is still an issue, might have to investigate the other forks..

**Comment by RehabMan** [comment]
Refer to example *.dsl in the repo for configuration items you might wish to change, especially if you have Thinkpad.
