### ISSUE TITLE
Caps Lock makes keyboard and mouse freeze

### ISSUE THREAD

**Issue by dreamwhite** [RehabMan/OS-X-Voodoo-PS2-Controller#188]
I'm using the latest release of VoodooPS2Controller on 10.14.5 (vanilla method). When I press twice the Caps Lock key it turns on and off the led. But if I repeat those steps for another two times the whole keyboard freezes with the mouse. What can it be? Do I have to edit something on the config.plist?

Thanks for your work @RehabMan

**Comment by RehabMan** [comment]
Please use the forums such that you can submit full details.  It is probably an issue with what you have installed and/or how you have installed it.
