### ISSUE TITLE
Dragging not working on TrackPoint (ThinkPad X200s)

### ISSUE THREAD

**Issue by ghost** [RehabMan/OS-X-Voodoo-PS2-Controller#29]
For some reason, trying to drag a window around only works sometimes - it appears that the times it does not work, the initial click is being repeated a few times a second while the button is being held down. After about 10 tries (it does vary) it works for the duration the button is held down and then goes back to the repeated clicking for the next press.

Works fine with an external USB mouse, so I'm thinking this is a driver issue.

This model does not have an internal trackpad, only the TrackPoint unlike other issues that have been reported.

**Comment by Polishapple** [comment]
for x200 and x220 the best is AcpiPS2Nub, ApplePS2Controller and old good thinkpadultranav.kext. (thinkpadultranav.kext is based on old voodoops2controller.kext so if rehabman could look inside that kext maybe he can solve tracking problem) :> So please RehabMan if you could it would solve many problems with thinkpads :>

**Comment by Polishapple** [comment]
Also i dicovered that after i disable touchpad (by prtsc button - nice thing RehabMan :>) Dragging works fine.

**Comment by RehabMan** [comment]
No hardware here like that.  No ability to test without hardware...

Those that have the hardware need to contribute.

**Comment by Polishapple** [comment]
I know nothing about kext development but i can provide as much information/files/dump as you need

**Comment by tluck** [comment]
i am using voodooPS2controller v1.8.5 on T420 which i believe has the same trackpad and trackpoint as x220 and dragging/moving a window or file (if thats what you mean by dragging) is working for me. in the preferences turn off dragging - so it means to drag, have to hold the left button down and then move the pointer. Note: i also implemented a flag in the DSDT to signify that my model is T420 and then the kexts pick up this to use certain config options in keyboard and trackpad (info.plist) that seem to work better for this trackpad.

**Comment by Polishapple** [comment]
tluck x220 use same trackpoint but diffrent touchpad, I also have t420 and trackpoint dragging works fine. When i disable touchpad trackoint drag works fine. Also i've tried your dsdt fix but there is no change (x220). I'd love to use voodoo from rehabman but simply old driver works better

**Comment by Polishapple** [comment]
For people with not working dragging i give you this :> http://www.insanelymac.com/forum/topic/285678-lenovo-thinkpad-t420-with-uefi-only/?p=2162721

**Comment by TheChuckster** [comment]
@RehabMan do you still need hardware to test with? I'd be happy to get you an x230 on eBay

**Comment by RehabMan** [comment]
Thanks for the offer, but the last thing I need is more laptops to work on...
I think my next laptop will likely have I2C, not PS2... and I'll be selling all my PS2-based laptops...

**Comment by TheChuckster** [comment]
@RehabMan can we discuss compensation? send me an email, I am hoping to get you on board with this!
