### ISSUE TITLE
alps acer no multitouch

### ISSUE THREAD

**Issue by NoobOFN** [RehabMan/OS-X-Voodoo-PS2-Controller#33]
Hi, I get simple mouse fonction and this:
ps2bl: KKCL, KKCM, KKQC methods not found in DSDT
VoodooPS2SynapticsTouchPad Version 1.8.9 loaded...
ApplePS2SynapticsTouchPad::probe entered...
VoodooPS2Trackpad: Identify bytes = { 0x0, 0x0, 0x64 }
VoodooPS2Trackpad: Identify TouchPad command returned incorrect byte 2 (of 3): 0x00
ApplePS2SynapticsTouchPad::probe leaving.
ApplePS2SentelicFSP::probe entered...

ApplePS2SynapticsTouchPad::probe leaving.
ApplePS2SentelicFSP::probe entered...
ApplePS2SentelicFSP::probe leaving.

ApplePS2ALPSGlidePoint::probe entered...

ApplePS2Keyboard::start leaving.
E7: { 0x73, 0x03, 0x50 } E6: { 0x00, 0x00, 0x64 }ALPS Device? no
ApplePS2ALPSGlidePoint::probe leaving.
VoodooPS2Mouse Version 1.8.9 loaded...

**Comment by cprovatas** [comment]
Hello @radut, I have installed your branch onto my Hackintosh, but get the following error: 

8/31/16 19:30:56.000 kernel[0]: VoodooPS2Trackpad: Identify TouchPad command returned incorrect byte 2 (of 3): 0x00

here are some other logs:

8/31/16 19:30:56.000 kernel[0]: Refusing new kext org.rehabman.voodoo.driver.PS2Controller, v1.8.12: a prelinked copy with a different executable UUID is already present.

8/31/16 19:30:43.276 sudo[20773]: charltonprovatas : TTY=ttys000 ; PWD=/Users/charltonprovatas/Documents/OS-X-Voodoo-PS2-Controller ; USER=root ; COMMAND=/sbin/reboot

8/31/16 19:30:56.000 kernel[0]: VoodooPS2TouchPad Version 1.9.0 loaded...
8/31/16 19:30:56.000 kernel[0]: VoodooPS2Mouse Version 1.8.11 loaded...


I am using a Lenovo y50 with ALPS trackpad.

Thank you very much for your help

**Comment by RehabMan** [comment]
Your logs show three different versions (1.8.12, 1.9.0, and 1.8.11) of the kexts...  
It is a very bad idea.

**Comment by cprovatas** [comment]
Thanks for your response RehabMan.  What would be the best way to uninstall the other versions and install only radut's branch for the trackpad?  All other functionality appears to be working fine despite the multiple versions installed.

Also, I have seen solutions for fixing this issue for Dells and other Laptops using ALPS by simply changing the byte values for the alps_model_data .  Is it possible that the fix could be that simple for ALPS on the y50? thank you.

**Comment by RehabMan** [comment]
Remove all PS2 kexts.  Install just radut's branch.  Or fresh install... (if you don't know where you installed the kexts, or can't fine them).

No experience with ALPS hardware.  And I really can't predict the future anyway...
