### ISSUE TITLE
Pointer isn't precise in Y580s

### ISSUE THREAD

**Issue by kristovzmk** [RehabMan/OS-X-Voodoo-PS2-Controller#37]
I got a problem with the trackpad and I think others Lenovo Y580 users could confirm this on OS X.

 I'll try to describe it as clear as I can.

 When I am in Win7 or in Win XP I can move the pointer to a position and then I can tap and it won't move a bit. It remains in the same position until I deliberately make a move with my fingers.
 So I can tap even hundreds times and it sticks as glue in the position I moved the pointer to.

 In OS X when I'm tapping the pointer moves itself. Sometimes even jump a 1cm down the screen.
 U know what I mean? I don't make a move I just tap and it moves...not much but it moves... preventing me from clicking in the exact position I want.
 For example I'm trying to close a window. I move the pointer to the red "x" button then I tap to close it and it's moving below the "x" itself so I need to move the pointer back to the red "x" and tap again, sometimes I need to repeat it twice, sometimes more. It's really annoying!!!

 Not sure if you can do anything about it but if yes then I'd move totally to OS X leaving Windows only for games or deleting it completely!

thank you.

**Comment by RehabMan** [comment]
Will be implementing a "threshold for movement" when I have time.

**Comment by icedman** [comment]
on XPS 13 9350, the pointer is still often jumpy on trackpad tap.

a quick hack that seems to help:

add on Touchpad.cpp 

    if (lastDY == 0) {
        if (dy > 80 || dy < -80)
            dy = 0;
        else
            dy = dy >> 2;
    }
    lastDY = dy;
    
    // dispatch dx/dy and current button status
    dispatchRelativePointerEventX(dx / divisorx, dy / divisory, buttons, now_abs);
    

there doesn't seem to be a problem on the x component.

**Comment by RehabMan** [comment]
There is no Touchpad.cpp in the project.
If you have a specific fix, file a pull request.

**Comment by icedman** [comment]
Ok. Will do.
Looks like the problem is indeed specific to my laptop. In the Bios Settings screen, the pointer is just as skippy. Somehow Windows 10 compensates.

**Comment by t-anjan** [comment]
I can confirm that I face the exact issue which is described in the first post. I am using 10.12.4 on Lenovo Yoga 710.

**Comment by RehabMan** [comment]
I made some changes in 1.9.2 for this specific issue.
