### ISSUE TITLE
Synaptics PointStyk not working on HP EliteBook 8570w (possibly others)

### ISSUE THREAD

**Issue by Viqsi** [RehabMan/OS-X-Voodoo-PS2-Controller#38]
While Synaptics' pointing stick on ThinkPads seems to work just fine (having tested it with a T61p), the same hardware on HP laptops doesn't seem to be recognized (in particular, on my Elitebook 8570w). It'll "function" if VoodooPS2Mouse is loaded *instead* of VoodooPS2Trackpad, but with one irritating quirk (click-and-drag doesn't work) and it also makes the Trackpad a hypersensitive minefield (due to the lack of palm compensation), so this is unfortunately not an acceptable workaround. :(

Since the hardware *does* sort-of function with existing drivers, is there any possible way to support this particular input device? Let me know if there's any information or testing you need done to make this happen and I'd be happy to help make it work. (I'd try working it myself, but my C++ experience is minimal at best. :( )

**Comment by RehabMan** [comment]
You can reopen if you have something to contribute. I have no hardware with the stick, so won't be doing any work with it.
