### ISSUE TITLE
sony vaio vpcf11pfx/h (alps touchpad and keyboard)

### ISSUE THREAD

**Issue by sormy** [RehabMan/OS-X-Voodoo-PS2-Controller#39]
sony vpcf11pfx/h issues:

Touchpad (ALPS):
* double tap didn't work in right way - can't normally select text and drag windows **(MAJOR ISSUE)**
* two finger scroll didn't work - i don't know if it's possible on that trackpad

Keyboard:
* it looks like keyboard not visible for os x, keyboard works but system every time tell me that "No keyboards have been found. Make sure your keyboard is discoverable." and Bluetooth Setup Assistant ask me to connect bluetooth keyboard. Can be fixed with workaround:
  * sudo defaults write /Library/Preferences/com.apple.Bluetooth BluetoothAutoSeekKeyboard '0'
  * sudo defaults write /Library/Preferences/com.apple.Bluetooth BluetoothAutoSeekPointingDevice '0'
* left WIN key and ALT key swapped and right ALT key and MENU key swapped
  * can be fixed in Preferences/Keyboard with Modifier keys override
  * can be fixed in Preferences/Keyboard with Modifier keys override
* pause/break works like brightness plus
* brightness minus (Fn + F3) and brightness plus (Fn + F4) didn't work

Is there any way to dump keys and remap them in plist?

**Comment by RehabMan** [comment]
There is an ALPS branch in this repo.  But the person who was originally responsible for the changes (bpedman) has dropped the project and no longer contributing.  Given that I don't have any ALPS hardware, I decided not to integrate it into the main branch.  Others may have forked that branch to create new versions with better support.  I'm not tracking it.
