### ISSUE TITLE
Jumping on top and bottom 1/3 of trackpad - Probook 4330s

### ISSUE THREAD

**Issue by noreye** [RehabMan/OS-X-Voodoo-PS2-Controller#4]
I've been using the trackpad a bit more lately (been using external mouse and monitor mainly) and I have noticed that if I move my finger slowly in the vertical direction the cursor seems to accelerate much faster (like a jump) at the the top and bottom 1/3 of the trackpad but the middle 1/3 is fine and the horizontal direction is fine.

It only appears to happen with 1 finger cursor and not the 2 finger scrolling. If I change the Tracking Speed settings in Sys Pref and use the slowest setting, the cursor speed is consistent across the entire vertical direction of the trackpad. The higher I set the Tracking Speed, the larger the acceleration jump in the top and bottom 1/3 of the trackpad, so if the setting is put on the fastest setting the cursor 'jumps' 1/4 of my screen.

original post at tonymac
http://www.tonymacx86.com/hp-probook/75649-new-voodoops2controller-keyboard-trackpad-130.html#post651264

**Comment by RehabMan** [comment]
This is due to things the trackpad firmware is doing in the horizontal (and probably vertical) scroll areas.  Will not attempt a fix/workaround.
