### ISSUE TITLE
Lenovo G580 FN keys

### ISSUE THREAD

**Issue by hackosx64** [RehabMan/OS-X-Voodoo-PS2-Controller#42]
Hello. My laptop is a Lenovo G580 I installed your latest VoodooPS2Controller.kext. everything works, except the brightness adjustment on the standard FN keys. I have FN+INS, FN+HOME. And should be FN+UN, FN+DOWN. How do I change it. As I understand it, the editing Info.plist VoodooPS2Keyboard.kext. Please tell me. Thanks in advance hackosx64.

**Comment by RehabMan** [comment]
See guide: http://www.tonymacx86.com/yosemite-laptop-support/152659-guide-patching-dsdt-ssdt-laptop-backlight-control.html
