### ISSUE TITLE
i need press fn when i want to put out number on the numeric keypad

### ISSUE THREAD

**Issue by panda199506** [RehabMan/OS-X-Voodoo-PS2-Controller#46]
my trackpad is syn and my trackpad can be used while i use your kext.I can also use the keyboard except that the numeric keypad was change to be direction key,and i need to put out number by pressing numeric key with fn.And i havd tried using elan kexts.then it canmake my keyboard normal,but i can not make my track work.

**Comment by RehabMan** [comment]
My guess is your problem is caused by Karabiner (formerly KeyRemap4MacBook).

**Comment by panda199506** [comment]
But I haven't used KeyRemap4MacBook.Can you tell me how can I fix this problem.

**Comment by RehabMan** [comment]
No idea.  Use the debug version to determine how the scan codes are being mapped.

**Comment by RehabMan** [comment]
No response.  Closing.
