### ISSUE TITLE
This kext doesn't load on a MSI GS60 laptop

### ISSUE THREAD

**Issue by LonghronShen** [RehabMan/OS-X-Voodoo-PS2-Controller#47]
This model of laptop uses a Elan keyboard and touchpad, but neither Voodoo-PS2-Controller nor Elan ps2 driver works. 
In the kernel log, I can't see anything about the PS2 driver even using the debug version of VoodooPS2Controller.kext. The VoodooPS2Deamon tells me that "Keyboard and touchpad not found".
By the way, my OSX version is 10.10.3, using UEFI+GPT+Clover.
DSDT hasn't been made.
Plus, MSI released an update for the BIOS and EC firmware. After update, the problem may be solved. I'll have a try.
Any idea about this?
Thank you!

EDIT: After adding a DSDT, the problem solved. But when I add some more patches to the DSDT, the PS2 keyboard and touchpad back to be unavailable again. I'll dive into the problem...

**Comment by LonghronShen** [comment]
By the way, my OSX version is 10.10.3, using UEFI+GPT+Clover.
DSDT hasn't been made.
Plus, MSI released an update for the BIOS and EC firmware. After update, the problem may be solved. I'll have a try.

**Comment by RehabMan** [comment]
Not an issue with the kext.
