### ISSUE TITLE
JIS(Japanese Industrial Standards) Correspondence?

### ISSUE THREAD

**Issue by hamaguchi** [RehabMan/OS-X-Voodoo-PS2-Controller#49]
Hi!
I am Japanese.

In Lenovo ThinkPad X1 Carbon Gen 3, it has become very indebted.

In can use the touch pad's a comfortable, 
but when you reboot the OS X, is what was set to JIS, will be the US keyboard (102?).

Is there a solution to this problem?

**Comment by LonghronShen** [comment]
Do you mean that you cannot save the keyboard layout settings?
You may extract the driver and find the Info.plist, search for something like "Use ISO Layout".
Then set it to <false />.
Try it.

**Comment by RehabMan** [comment]
SysPrefs->Keyboard->Input Sources.
