### ISSUE TITLE
Thinkpad trackpad scroll only

### ISSUE THREAD

**Issue by tertiumsquid** [RehabMan/OS-X-Voodoo-PS2-Controller#54]
Is there a way of disabling regular mouse movement and clicking on the trackpad and using it for scrolling only (1 or 2 finger), while keeping the trackpoint enabled, or can this be implemented?

Alternately, is there a way of disabling the trackpad completely, while still allowing middle mouse button scrolling?  If I disable the trackpad in the bios, scrolling stops working, and I haven't found a "disable" in the Info.plist that works for my system.  

I'm on a Thinkpad X220 4290-BY7, latest VoodooPS2 (2015-05-02), and Mac OS 10.10.1, if that helps.

**Comment by RehabMan** [comment]
It could be implemented.  Source code is available.  Not possible by only changing Info.plist.
