### ISSUE TITLE
x220 Thinkpad trackpoint has difrent speed than trackpad

### ISSUE THREAD

**Issue by Polishapple** [RehabMan/OS-X-Voodoo-PS2-Controller#59]
Hi, the newest voodoops2 fixed the problem with moving windows, but now the trackpad has a perfect speed, but tracpoint is way to fast. Even after changing speed in System Preferences its still to fast, and trackpad is slow.

**Comment by RehabMan** [comment]
Look at MouseMultiplierX and MouseMultiplierY.

**Comment by chuckhacker** [comment]
If it helps, I set MouseMultiplierX and MouseMultiplierY to 2 (down from 20), and now the trackpoint is actually very useable (before, the slightest touch would send the cursor flying across the screen!). I also set the scroll multipliers to 2 each, and now the middle click scrolling is also very usable, unlike before.
