### ISSUE TITLE
I try to swap CapsLock and Escape, but something went wrong.

### ISSUE THREAD

**Issue by ooopscc** [RehabMan/OS-X-Voodoo-PS2-Controller#6]
Hey,

I just cloned the newest version of this code. 

I am a _Vimer_, What I want to do is to swap `Caps Lock` and `Escape`. So I followed you code, and simply made some changes :
##### Enveriments:
- Xcode 5.0.1
- Mac 64-bit 
- Windows Version Chameleon 2246
- no dsdt
##### VoodooPS2Keyboard.cpp

```
#define kSwapCapsLockLeftControl            "Swap capslock and left control"
#define kSwapCapsLockEscape                 "Swap capslock and escape" 
#define kSwapCommandOption                  "Swap command and option"
```

![](http://ww4.sinaimg.cn/large/7e921c39jw1ea5nt0457xj20iy027dg6.jpg)

```
    setProperty(kSwapCapsLockLeftControl, xml->isTrue() ? kOSBooleanTrue : kOSBooleanFalse);
}

//////////////////////////// ooops added ////////////////////////////
xml = OSDynamicCast(OSBoolean, dict->getObject(kSwapCapsLockEscape));                   
if (xml) {
    if (xml->isTrue()) {
        _PS2ToADBMap[0x3a]  = _PS2ToADBMapMapped[0x01];
        _PS2ToADBMap[0x01]  = _PS2ToADBMapMapped[0x3a];
    }
    else {
        _PS2ToADBMap[0x3a]  = _PS2ToADBMapMapped[0x3a];
        _PS2ToADBMap[0x01]  = _PS2ToADBMapMapped[0x01];
    }
    setProperty(kSwapCapsLockEscape, xml->isTrue() ? kOSBooleanTrue : kOSBooleanFalse);
} 
//////////////////////////// until here ////////////////////////////

xml = OSDynamicCast(OSBoolean, dict->getObject(kSwapCommandOption));
```

![](http://ww4.sinaimg.cn/large/7e921c39jw1ea5nt12ty7j20m50di768.jpg)   

And also these three plist files: 
##### VoodooPS2Keyboard-Info.plist

![](http://ww1.sinaimg.cn/large/7e921c39jw1ea5msrmiiwj20os0303z1.jpg)

Then, I choose **All** scheme and run, no any errors or warnings, build result:

![](http://ww4.sinaimg.cn/mw690/7e921c39jw1ea5nowi5j9j207704o0sw.jpg)

Replace _VoodooPS2Controller.kext_ with the one built just now, also _VoodooPS2Daemon_ ,_synapticsconfigload_ and _VoodooPS2synapticsPane.prefPane_

After repair kext premissions, update system cache, reboot with -f

I found that the feature I want does work, but there are something wrong with other keyremaps, for example 
- **Swipe Up** becomes to `⌘↑`(command up)
- **Swipe Down** becomes to `⌥↓` (option down)
- **Command Shift 3, 4** does not work either 

but I didn't even touch that part of code or setting.

This is all what I did, is there something wrong or miss that leads to a mess?
Also, would you please add the feature for Vimers in the next release of VoodooPS2, thanks!

**Comment by aizigao** [comment]
in 10.12.2 I can't change caps to ctrl use system preference

**Comment by RehabMan** [comment]
> in 10.12.2 I can't change caps to ctrl use system preference

It is because of work around for capslock bug introduced in 10.12.

**Comment by aizigao** [comment]
I have seen the info.plist , can I use this 
```xml
<key>Swap capslock and left control</key>
<false/>
```
😄

**Comment by RehabMan** [comment]
It swaps ADB codes.  It should still work.
Swapping keys can also be done with "Custom ADB Map"
You can also change such settings with ACPI.  Refer to *.dsl in the VoodooPS2Controller github repo for examples of ACPI overrides of Info.plist settings.

**Comment by RehabMan** [comment]
Closing.  No plans to implement as the feature can be implemented with ACPI based configuration.
