### ISSUE TITLE
Dragging with trackpoint problem in Lenovo X220

### ISSUE THREAD

**Issue by Polishapple** [RehabMan/OS-X-Voodoo-PS2-Controller#65]
Hi, there is a problem with dragging in x220. Trackpoint and touchpad are from Synaptic. 
When i try dragg somethig 9/10 times the window will not be "attached" to cursor or it will go to full screen - like i clicked multiple times. The problem is gone when i disable touchpad by PrtSc.

**Comment by RehabMan** [comment]
Use the debug version to determine what is wrong.  I have no such hardware to reproduce the problem.  I'll integrate a fix that makes sense and is coded carefully.
