### ISSUE TITLE
Can I use two finger gestures ?

### ISSUE THREAD

**Issue by MichelBahl** [RehabMan/OS-X-Voodoo-PS2-Controller#66]
I am using an Lenovo Y70.
The trackpad is working except multitouch gestures,
what do I need to do to make it work ?

**Comment by RehabMan** [comment]
Two finger gestures:
- two fingers scroll
- two finger tap for right click
- two finger double tap for double right click

It is not true multitouch, but rather simulation.

**Comment by MichelBahl** [comment]
Unfornately I can't get it working.
If I install voodoo-ps2 the basics are working the touchpad behaves like a mice.

It's really annoying when I want to scroll, I always need to hit the small scroll
bar.
I downloaded the source code for setup remote kext debugging,
but it seems since OSX 10.9 a developer certificate is required.

Can you give me tip, maybe I did something wrong at installation.

**Comment by RehabMan** [comment]
Perhaps you don't have a Synaptics trackpad.
