### ISSUE TITLE
ALPS on 1.8.15? ... can the trackpad from a Dell M4800 be supported on later release?

### ISSUE THREAD

**Issue by tluck** [RehabMan/OS-X-Voodoo-PS2-Controller#67]
I found that an older version 1.8.9 (included in Pokenguyens HVT) will work - but doesn't have some of the nice features (2 finger swipe up down). Was curious what it would take to debug/modify to work on this pad? thoughts? i can provide dumps and or code testing etc... 

thoughts?

**Comment by RehabMan** [comment]
The ALPS branch is bpedman_merge.  I have no ALPS hardware, therefore am not doing any work on it, although I sometimes merge the master branch into it.
