### ISSUE TITLE
T440p middle button scroll

### ISSUE THREAD

**Issue by Polishapple** [RehabMan/OS-X-Voodoo-PS2-Controller#68]
Hi, the buttons on upper part of touchpad (they are for trackpoint in Thinkpad T440p aren't working. (only left click is recognized). I'm using the newest version of VoodooPS2Controller
If any file is needed tell me :> (log? debug somethink?):>

**Comment by RehabMan** [comment]
I don't have the hardware.  I suggest you do some logging of the packets and see if you can determine which changes are needed in the code.

**Comment by RehabMan** [comment]
Closing due to lack of feedback/information.  Since I don't have the hardware, not planning to do anything here myself.
