### ISSUE TITLE
Thinkpad use Trackpoint only

### ISSUE THREAD

**Issue by seff** [RehabMan/OS-X-Voodoo-PS2-Controller#70]
I use Lenovo T420, both Touchpad and Trackpoint work fine, I can use Win+SysRq to toggle Touchpad too. But I never use Touchpad, so I must press the two keys after OS started every time.

Whether I could change the Info.pkist to disabke Touchpad default like in Windows.

thx.

**Comment by RehabMan** [comment]
You can turn both off with PrtSc.
