### ISSUE TITLE
TrackPoint inaccurate on X220 unless touchpad is disabled in BIOS

### ISSUE THREAD

**Issue by bailtree** [RehabMan/OS-X-Voodoo-PS2-Controller#71]
But when it is disabled, I can no longer scroll with the middle button(one below the trackpoint). When both are enabled, trackpoint is inaccurate but touchpad is accurate (yet slow, I have to make tracking speed the lowest for trackpoint to be remotely accurate)

**Comment by RehabMan** [comment]
Source code is available.  I have no such hardware to test with it.  If you come up with a fix, please post a pull request.

**Comment by bailtree** [comment]
it was because I didn't have the dsdt.aml ... oops
