### ISSUE TITLE
Printscreen toggles trackpad input

### ISSUE THREAD

**Issue by mach-kernel** [RehabMan/OS-X-Voodoo-PS2-Controller#73]
Hi @RehabMan,

Thank you very much for this open source driver, I *extremely* appreciate all of your work. As for this, is this a bug or a feature. I kinda like this behavior but I wonder if there's anything that needs fixing. I'd be open to making some contributions.

Thanks!

**Comment by RehabMan** [comment]
Feature.

**Comment by RehabMan** [comment]
You can change the mapping in ACPI.  Look at my u430 repo for an example, or even SSDT-PrtSc-F13.dsl in the github repo.
