### ISSUE TITLE
TrackPoint Scrolling is non-functional if the trackpad is disabled in BIOS (T420)

### ISSUE THREAD

**Issue by SilverEzhik** [RehabMan/OS-X-Voodoo-PS2-Controller#76]
**Expected behavior:** TrackPoint scrolling works.

**Actual behavior:** TrackPoint scrolling does not work. Holding the middle button does not 'freeze' the mouse pointer in place. A middle click is still registered, however.

**Workaround:** Instead of disabling the trackpad in BIOS, disable it in the system by pressing the Print Screen.

**Comment by RehabMan** [comment]
By design.
No possibility for your trackpoint to send PS2 data if it is disabled.
