### ISSUE TITLE
Cube i7 problems

### ISSUE THREAD

**Issue by byzyn4ik** [RehabMan/OS-X-Voodoo-PS2-Controller#78]
I don't found a key in plist to disable very bad feature of driver with my trackpad. My trackpad was recognized as mouse , all works but when i am moving finger from top to bottom they sending cmd+z combination. When moving from left to right  sending cmd+backspace  , from right to left cmd+c , from bottom to top - nothing all works like i need. I have small knowledge of c++ but big knowledge of obj-c and c , so if you can give me advice where i need to disable this , i will try.

**Comment by RehabMan** [comment]
Define 'they' in 'they are sending'.

**Comment by byzyn4ik** [comment]
May be driver sends cmd-z when trackpad moving from absolute top to bottom (if a moving trackpad from center i have no problems).

**Comment by RehabMan** [comment]
My code doesn't.  It is possible (but a bit strange) that your trackpad firmware does it though.

At any rate, not related to this project.
