### ISSUE TITLE
external USB keyboard?

### ISSUE THREAD

**Issue by khalidchawtany** [RehabMan/OS-X-Voodoo-PS2-Controller#79]
Hi all,
Is this driver PS2 specific, as the name implies, or I can use it for USB keyboards too?

I ask about this, as I have an HP Pavilion g6 laptop and the internal keyboard key-codes are shown when I install the debug version. However, my USB keyboard key-codes are not shown as if no key is pressed.

Thanks.

**Comment by RehabMan** [comment]
This driver is for PS2 only.
