### ISSUE TITLE
Custom keyboard mapping won't work

### ISSUE THREAD

**Issue by Peluko** [RehabMan/OS-X-Voodoo-PS2-Controller#84]
Hello. I'm trying to remap Capslock to Esc using the custom keyboard mapping feature and it doesn't work for me. I've followed the instructions found on the wiki, but Voodoo PS2 ignores whatever I put on the `Custom PS2 Map` section. I haven't found any errors on the system logs, and I don't kwon where to look. 
How should I debug this?

Thanks.

**Comment by RehabMan** [comment]
You should debug by looking at the debug logs.
