### ISSUE TITLE
A lot of problem at Sierra

### ISSUE THREAD

**Issue by vaslobas** [RehabMan/OS-X-Voodoo-PS2-Controller#85]
Hello.

I recently update my hack to 10.12 and i got this:
1. Lost function fey functionality. Built-in volumes/brightness control now doesnt works.
2. Touchpad doesnt work properly and touchpad's prefpane in system preference doesn't work. Only grey blank window.
![screen shot 2016-09-06 at 01 50 34](https://cloud.githubusercontent.com/assets/6232484/18257920/5200e27c-73d4-11e6-80ec-057ef02475c2.png)

Before update to 10.12 all was woks like a charm.

**Comment by Polishapple** [comment]
We're on same boat - same thing happend

**Comment by ThisIsQasim** [comment]
Yup. I can confirm that happened to me as well.

**Comment by devbau** [comment]
Download the patched macOS Sierra Trackpad prefPane*, unzip and move to System/Library/PreferencePanes
Note that this patched Trackpad prefPane will need to be opened once after each restart to make its settings active again. We’re working on a better solution.

* http://www.mediafire.com/download/8r6ew57721w5r82/macOS_Sierra_patched_Trackpad_prefPane.zip
(Source: http://x220.mcdonnelltech.com/thinkpad-x220-macos-sierra-installation/)

**Comment by RehabMan** [comment]
Guys... These problems are all well known.

**Comment by Polishapple** [comment]
So... We shouldn't post issues?

**Comment by RehabMan** [comment]
Obviously, the issue is posted.  But it is not a problem with this kext.  
You can set your needed settings with ioio from a LauchDaemon.

**Comment by TheCuriousHacker** [comment]
CAPSLOCK does not work properly..

**Comment by RehabMan** [comment]
The capslock problem is well known.   No solution at this time.

**Comment by TheCuriousHacker** [comment]
> Obviously, the issue is posted. But it is not a problem with this kext.
> 
> You can set your needed settings with ioio from a LauchDaemon.

Please can you give link to the instructions?

**Comment by RehabMan** [comment]
ioio is available from my github.
You can read about LaunchDaemon setup on the internet.

**Comment by L1v1ng0nThe3dge** [comment]
On Lenovo Thinkpad X220, volume keys don't work. Same problem with the trackpad. Just reporting findings. Upgraded to Sierra yesterday.

**Comment by midi1996** [comment]
Apparently 10.12.1 fixes the Volume and Brightness issues, however CAPSLOCK issues is still present as well as the Touchpad prefpan

**Comment by usr-sse2** [comment]
#89 resolves the issue with Touchpad prefpane.

**Comment by RehabMan** [comment]
I will be updating the kext soon with some of usr-sse2 changes and my own changes for brightness.
