### ISSUE TITLE
Multitouch Gesture Not Working on Alps Pointing Device

### ISSUE THREAD

**Issue by norandomtechie** [RehabMan/OS-X-Voodoo-PS2-Controller#88]
VoodooPS2Trackpad/Mouse does not support even two-finger scrolling on macOS Sierra with the Alps Pointing Device touchpad on HP Pavilion TS 14 Notebook PC n020se. Is there an extra setting I have to enable first or is support still being added?

**Comment by sonvirgo** [comment]
This one, 2 fingers scrolling but very unstable http://forum.osxlatitude.com/index.php?/topic/8285-refined-alps-touchpad-driver/

**Comment by RehabMan** [comment]
I have no ALPS hardware, so will not be addressing any issues with it.
There is the bpedman_merge branch, but it was abandoned by the author (bpedman).
There may be other forks that have better ALPS support.
