### ISSUE TITLE
Lenovo T430 Touchpad left click issue on 10.12.1

### ISSUE THREAD

**Issue by phen0menal** [RehabMan/OS-X-Voodoo-PS2-Controller#95]
After updating to 10.12.1, the left click is being registered as a Ctrl + Left Click on what I do, dock items experience that effect, any other program that has typing included, won't allow me to type because of some lockup that occurs, so focusing on the desktop while the program is open, gets my typing going. Sometimes when I open a window, It automatically starts dragging the window. This all happens about 3-5 seconds into the desktop but prior wise, it works perfectly before the issue kicks in.

**Comment by RehabMan** [comment]
No such issue here.
