### ISSUE TITLE
How can I build the prefpane?

### ISSUE THREAD

**Issue by JurekRaben** [RehabMan/OS-X-Voodoo-PS2-Controller#97]
How can I build the prefpane? The Apple touchpad prefpane does not detect anything

**Comment by RehabMan** [comment]
I will be updating for Sierra soon.  It will use the system prefpane (new style), as provided with changes that usr-sse2 made (will be cherry picking the needed changes).

The prefpane code here has not been updated for recent SDKs, and needs a lot of work to be useable anyway.  No plans to do it.
